
###
//--------------Apply for a Team--------------
POST http://localhost:3001/api/teams/apply/64606a37a33a1f2ecac18628
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NjBlYmUyYzk0YzEwZWJkZjA0NmI4ZSIsImlhdCI6MTY4NDA3MzQ1NCwiZXhwIjoxNjg2NjY1NDU0fQ.2ty9S9EbaSmfoCO-FS4_cwiPUebkYxkTe9tXruNgEwc
Content-Type: application/json

{
  "letter":"sads",
  "preferredRole":"Phoenix",
  "links": [
    {
      "title":"adsdsadsadasdas",
      "link":"sdadasdas.co.il"
      }
      ]
}
