#################
POST http://localhost:3001/api/auth/tryLogin/daneles271@gmail.com/DangiG

###########
POST http://localhost:3001/api/auth/finalLogin/daneles271@gmail.com/106998


Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NjA0NjE4MDE3ZjU3NGRmZjQ0NjU5NSIsImlhdCI6MTY4NDAzMTAxMiwiZXhwIjoxNjg2NjIzMDEyfQ.8YCdTGAjSRSqBjhNOooopmua-75C-PmLl70nYH7qJro