#################
POST http://localhost:3001/api/auth/tryLogin/inviteserv@gmail.com/sqavekiller

###########
POST http://localhost:3001/api/auth/finalLogin/inviteserv@gmail.com/555428




Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NjA0NjE4MDE3ZjU3NGRmZjQ0NjU5NSIsImlhdCI6MTY4NDAzMTAxMiwiZXhwIjoxNjg2NjIzMDEyfQ.8YCdTGAjSRSqBjhNOooopmua-75C-PmLl70nYH7qJro