

###
//---------------------Create A Team------------------------
POST http://localhost:3001/api/teams/createTeam
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NjA0NjE4MDE3ZjU3NGRmZjQ0NjU5NSIsImlhdCI6MTY4NDAzMTAxMiwiZXhwIjoxNjg2NjIzMDEyfQ.8YCdTGAjSRSqBjhNOooopmua-75C-PmLl70nYH7qJro
Content-Type: application/json

{
  "name": "Team-O1",
"region":"Europe"
}

###
//Apply for a Team
POST http://localhost:3001/api/teams/apply/64606a37a33a1f2ecac18628
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NjA0NjE4MDE3ZjU3NGRmZjQ0NjU5NSIsImlhdCI6MTY4NDAzMTAxMiwiZXhwIjoxNjg2NjIzMDEyfQ.8YCdTGAjSRSqBjhNOooopmua-75C-PmLl70nYH7qJro
Content-Type: application/json

{
  "letter":"sads",
  "links": [
    {
      "title":"adsdsadsadasdas",
      "link":"sdadasdas.co.il"
      }
      ]
}


###########
//Search for a teams
GET http://localhost:3001/api/teams